import {
  LayoutDashboard,
  FolderKanban,
  ListTodo,
  Users,
  CalendarDays,
  BarChart3,
  Bell,
  Settings,
  ChevronDown,
  Star,
  ClipboardList,
  Route,
  Waypoints,
  GitBranch,
  Bug,
  PackageOpen,
  Activity,
  Code,
  SendHorizontal,
  SunDim,
  Moon,
  X,
  Menu,
} from "lucide-react";

export const icons = {
  dashboard: LayoutDashboard,
  projects: FolderKanban,
  tasks: ListTodo,
  team: Users,
  calendar: CalendarDays,
  analytics: BarChart3,
  notifications: Bell,
  settings: Settings,
  chevronDown: ChevronDown,
  star: Star,
  clipboardList: ClipboardList,
  route: Route,
  gitBranch: GitBranch,
  bug: Bug,
  packageOpen: PackageOpen,
  activity: Activity,
  code: Code,
  waypoints: Waypoints,
  sendHorizontal: SendHorizontal,
  sunDim: SunDim,
  moon: Moon,
  x: X,
  menu: Menu,
};

export type IconName = keyof typeof icons;
